### ISSUE TITLE
I believe the mod conflicts a bit with other settings

### ISSUE THREAD

**Issue by rubyFeedback** [Austin-BG/HTaM#10] opened 2023-08-17 00:08 UTC
Today I finally found the bank on the bottom right corner. I am certain it did not show up
before due to other mods I think.

But now I have another problem: I can not enter the tent in the middle there. Normally I can enter
it  and obtain Aerie, but this time no stair-icon with the mouse shows up. I believe some coordinates
may have changed due to that. It may also not be the fault of HTaM but of some other mod but
either way something isn't quite right. Some mod confuses the coordinates I think. I can talk
to the guard outside and the boy missing the mother, but I can not actually enter the tent.

The idea of moneylenders is quite neat. I believe I actually also already played some parts of
this mod before, some orcs show up right?

**Comment by Austin-BG** [comment] 2023-11-13 13:07
Hello! Regarding the entrance to the circus on the Promenade, this is not related to the HtaM mod, since this entry point is not affected anywhere in it, and the entrance to the bank is added in a completely different place, in the southern part of the map. This problem is caused by some other mod or compatibility issues in a large selection of mods.

**Comment by Austin-BG** [comment] 2023-11-14 10:40
As for the orcs - yes, these orcs are part of one of the quest branches of the second component of the mod (which adds the bank). By the way, if the player chooses to help Korgan and Owny’s group, then a parallel quest line will be involved and then you will not meet orcs in the game. These two branches are united only at the very end, when both branches will have the quest "Pirate Legacy", completed in Brinnlaw. This is a rather complex system of parallel quests, which I coded for a long time and painfully, heh (

**Closed as completed** 2024-08-06 15:42 UTC
